### ISSUE TITLE
Add app to B-Hackers Store

### ISSUE THREAD

**Issue by sunsetsonwheels** [zjyl1994/KaiAuth#3]
The current sideloading method is preventing a number of people from installing this awesome app. As such, it'd be appreciated if you can submit the app to our [B-Hackers Store](https://gitlab.com/banana-hackers/store-db/-/tree/master/apps) for easier installation for people on KaiOS forks such as GerdaOS.

If possible, you can create GitHub releases of your app and I can maintain your app entry on the B-Hackers Store.

Regards,
jkelol111

**Comment by zjyl1994** [comment]
I have submitted it to KaiStore, waiting for their review.
I am happy to submit this applications to the B-Hackers Store, but I don’t know what to do.

**Comment by zjyl1994** [comment]
I filled out this yml file in the format of b-hackers store, but I do n’t have a gitlab account, can you help me put it into the store database?
[kaiauth-yml.zip](https://github.com/zjyl1994/KaiAuth/files/4434053/kaiauth-yml.zip)

**Comment by sunsetsonwheels** [comment]
> I filled out this yml file in the format of b-hackers store, but I do n’t have a gitlab account, can you help me put it into the store database?
> [kaiauth-yml.zip](https://github.com/zjyl1994/KaiAuth/files/4434053/kaiauth-yml.zip)
> 

Sure, will do tomorrow.

**Comment by sunsetsonwheels** [comment]
I added your yml file to the Store, will close this issue now.
